apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: placement-pro

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - pvc.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - ingress.yaml
