apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: placement-pro-pvc
  namespace: placement-pro
  labels:
    app.kubernetes.io/name: placement-pro
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
