apiVersion: v1
kind: Secret
metadata:
  name: placement-pro-secrets
  namespace: placement-pro
  labels:
    app.kubernetes.io/name: placement-pro
type: Opaque
stringData:
  SECRET_KEY: "placement-pro-secret-key-k8s-prod-2026"
  JWT_SECRET: "placement-pro-jwt-secret-key-k8s-prod-2026"
